#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/index.html;
echo "Hello World!" >> /etc/nginx/html/index.html;
printf %s "server {
	listen     80 default_server;
	listen     [::]:80 default_server;
	root       /etc/nginx/html;
	index      index.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=FEbBEAzqqtg;
	}	
}
" > /etc/nginx/sites-available/default

sudo service nginx restart

