#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using if
a=1
while [ $a -le 10 ]
do
    if [[ $a == 9 ]]
    then
        echo "Hi";
		((a++))
    else
        echo "Best School";
		((a++))
    fi
done
